# Generated by Django 4.0.5 on 2022-06-24 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('department', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to=None)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('student_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.employee')),
            ],
        ),
    ]
