# Generated by Django 4.0.5 on 2022-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=None)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('many', models.ManyToManyField(to='st.employee')),
            ],
        ),
    ]
