# Generated by Django 4.0.5 on 2022-06-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='many',
            field=models.ManyToManyField(to='st.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_is',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.student'),
        ),
    ]
