# Generated by Django 4.0.5 on 2022-06-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_alter_object_many_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='st.student'),
        ),
    ]
