# Generated by Django 4.0.5 on 2022-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_alter_student_is_active_alter_student_student_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(null=True, upload_to='downloads'),
        ),
    ]
