# Generated by Django 4.0.5 on 2022-07-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
